apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: skaffold-example
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: nodejs-app
      docker:
        dockerfile: Dockerfile
    - image: alpine-curl
      docker:
        dockerfile: Dockerfile.verify
  local:
    useDockerCLI: false
    useBuildkit: true
test:
  - image: nodejs-app
    structureTests:
      - './structure-test/*'
    custom:
     - command: "npm --prefix ./src test"
       dependencies:
          paths:
            - "**/*.js"
deploy:
  helm:
    releases:
      - name: nodejs-app
        chartPath: helm/nodejs-app
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_nodejs_app}}"
          image.tag: "{{.IMAGE_DIGEST_nodejs_app}}"
        setValues:
          env: "local"
        valuesFiles:
          - helm/nodejs-app/values.yaml
verify:
  - name: alpine-curl
    container:
      name: alpine-curl
      image: "alpine-curl"
      command: ["/bin/sh"]
      args: ["-c", "curl -XGET http://nodejs-app-service:8081"]
    executionMode:
      kubernetesCluster: {}

profiles:
  - name: dev
    build:
      tagPolicy:
        inputDigest: {}
      artifacts:
        - image: nodejs-app
          docker:
            dockerfile: Dockerfile
        - image: alpine-curl
          docker:
            dockerfile: Dockerfile.verify
      local:
        useDockerCLI: false
        useBuildkit: true
    test:
      - image: nodejs-app
        structureTests:
          - './structure-test/*'
    deploy:
      helm:
        releases:
          - name: nodejs-app
            chartPath: helm/nodejs-app
            createNamespace: true
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_nodejs_app}}"
              image.tag: "{{.IMAGE_DIGEST_nodejs_app}}"
            setValues:
              env: "dev"
            valuesFiles:
              - helm/nodejs-app/values-dev.yaml
    verify:
      - name: alpine-curl
        container:
          name: alpine-curl
          image: "alpine-curl"
          command: ["/bin/sh"]
          args: ["-c", "curl -XGET http://nodejs-app-service:8081"]
        executionMode:
          kubernetesCluster: {}
