apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: skaffold-example
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: nodejs-app
      docker:
        dockerfile: Dockerfile
    - image: alpine-curl
      docker:
        dockerfile: Dockerfile.verify
  local:
    useDockerCLI: false
    useBuildkit: false
test:
  - image: nodejs-app
    structureTests:
      - './structure-test/*'
    custom:
     - command: "npm --prefix ./src test"
       dependencies:
          paths:
            - "**/*.js"
deploy:
  helm:
    releases:
      - name: nodejs-app
        chartPath: helm/nodejs-app
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_nodejs_app}}"
          image.tag: "{{.IMAGE_DIGEST_nodejs_app}}"
        valuesFiles:
          - helm/nodejs-app/values.yaml
manifests:
  helm:
    flags:
        upgrade:
        - --wait
        - --timeout=20m
        install:
        - --wait
        - --timeout=20m
    releases:
      - name: nodejs-app
        chartPath: helm/nodejs-app
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_nodejs_app}}"
          image.tag: "{{.IMAGE_DIGEST_nodejs_app}}"
        valuesFiles:
          - helm/nodejs-app/values.yaml
verify:
  - name: alpine-curl
    container:
      name: alpine-curl
      image: "alpine-curl"
      command: ["/bin/sh"]
      args: ["-c", "curl -XGET http://nodejs-app-service:8081"]
    executionMode:
      kubernetesCluster: {}

profiles:
  - name: docker
    build:
      tagPolicy:
        inputDigest: {}
      artifacts:
        - image: nodejs-app
          docker:
            dockerfile: Dockerfile
        - image: alpine-curl
          docker:
            dockerfile: Dockerfile.verify
      local:
        push: false
        useDockerCLI: false
        useBuildkit: false
    test:
      - image: nodejs-app
        structureTests:
          - './structure-test/*'
        custom:
        - command: "npm --prefix ./src test"
          dependencies:
              paths:
                - "**/*.js"
    deploy:
      docker:
        images: [nodejs-app, alpine-curl]

  - name: dev
    build:
      tagPolicy:
        inputDigest: {}
      artifacts:
        - image: gcr.io/flyr-gcr/nodejs-app
          docker:
            dockerfile: Dockerfile
        - image: alpine-curl
          docker:
            dockerfile: Dockerfile.verify
      local:
        useDockerCLI: false
        useBuildkit: true
    test:
      - image: gcr.io/flyr-gcr/nodejs-app
        structureTests:
          - './structure-test/*'
    deploy:
      helm:
        releases:
          - name: nodejs-app
            chartPath: helm/nodejs-app
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_nodejs-app}}"
              image.tag: "{{.IMAGE_DIGEST_nodejs-app}}"
            valuesFiles:
              - helm/nodejs-app/values-dev.yaml
    manifests:
      helm:
        releases:
          - name: nodejs-app
            chartPath: helm/nodejs-app
            valuesFiles:
              - helm/nodejs-app/values-dev.yaml
    verify:
      - name: alpine-curl
        container:
          name: alpine-curl
          image: "alpine-curl"
          command: ["/bin/sh"]
          args: ["-c", "curl -XGET http://nodejs-app-service:8081"]
        executionMode:
          kubernetesCluster: {}
