apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: nodejs-app
        env: {{ .Values.env }}
    spec:
      containers:
      - name: nodejs-app
        image: {{ template "helpers.IMAGE" . }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:  
          httpGet:
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer
